# Rust formatting configuration (stable-compatible)
# See https://rust-lang.github.io/rustfmt/ for all options

edition = "2021"

# Line width
max_width = 100

# Formatting style
use_small_heuristics = "Default"
fn_call_width = 80
attr_fn_like_width = 80
struct_lit_width = 40
struct_variant_width = 40
array_width = 80
chain_width = 80

# Indentation
tab_spaces = 4
hard_tabs = false

# Imports
reorder_imports = true

# Misc
remove_nested_parens = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
